# Generated by Django 5.2.6 on 2025-09-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
