# Generated by Django 5.2.6 on 2025-09-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
